on:
  schedule:
  - cron:  "0 10 */7 * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/addyosmani/puppeteer-webperf.git"
        source_branch: "master"
        destination_branch: "upstream"
        github_token: ${{ secrets.GITHUB_TOKEN }}
